### ISSUE TITLE
Pastel wood blocks

### ISSUE THREAD

**Issue by HiItsDevin** [devOS-Sanity-Edition/pastelwonderland#14]
use a placeholder textures for this one please

**Comment by Stereo528** [comment]
![2021-01-24_10 58 11](https://user-images.githubusercontent.com/52116771/105639088-7c7f6980-5e33-11eb-917c-9e5ce957dc17.png)
we have a log

one problem
![2021-01-24_10 59 27](https://user-images.githubusercontent.com/52116771/105639093-85703b00-5e33-11eb-9d6f-a193ad3e3d3b.png)

**Comment by HiItsDevin** [comment]
excuse me did we invent a new type of tree

**Comment by Stereo528** [comment]
yea its called "A treee that cant keep its leaves"
