### ISSUE TITLE
New trees

### ISSUE THREAD

**Issue by HiItsDevin** [devOS-Sanity-Edition/pastelwonderland#18]
please also use placeholder textures for this one until #15 is resolved

**Comment by HiItsDevin** [comment]
this accidently happened during one of my worldgen struggles
![javaw_K8VIWbDkny](https://user-images.githubusercontent.com/30705254/105416265-bad81700-5bee-11eb-822c-efc8ee9e9980.png)

**Comment by Stereo528** [comment]
isnt this basically done with the trees I did like 9871229487 years ago?

**Comment by HiItsDevin** [comment]
yes but we still need to add crimson-like trees

**Comment by HiItsDevin** [comment]
Shelved for now, waiting for 1.17, also because Mojang is really fucking cursed with Crimson Trees
