### ISSUE TITLE
[BUG] Fabric Rendering API accessed in common, causing crash on server

### ISSUE THREAD

**Issue by Oliver-makes-code** [devOS-Sanity-Edition/pastelwonderland#39]
**Describe the bug**
Fabric Rendering API is being accessed on server, causing a crash
<https://github.com/devOS-Sanity-Edition/pastelwonderland/blob/1.18.x/src/main/java/one/devos/nautical/pastelwonderland/common/PastelwonderlandBlocks.java#L110-L111>

**Desktop (please complete the following information):**
 - Minecraft Version 1.18.2
 - Mod Version Latest github actions

**Additional context**
Needed for BlanketCon

**Comment by asoji** [comment]
Oh uh, please do not run current builds of Pastel Wonderland, they are being actively rewritten in the background and is NOT intended for gameplay yet. Sorry! I kinda estimate that we'll have a mostly functional playable build by the end of the month, but that's not a guarentee.
