### ISSUE TITLE
Code reorganization

### ISSUE THREAD

**Issue by HiItsDevin** [devOS-Sanity-Edition/pastelwonderland#4]
Reorganize code into different class files and make sure they don't break

**Comment by HiItsDevin** [comment]
Apparently we're doing this again on the Rewrite branch

**Comment by Stereo528** [comment]
:)

**Comment by HiItsDevin** [comment]
I'm currently working on the Kotlin rewrite branch seen on the [rewrite-kotlin](https://github.com/devOS-Sanity-Edition/pastelwonderland/tree/rewrite-kotlin) branch so that's cool uwu
